export default {
    users: [],
    user: null,
    pets: [],
    petsHome: [],
    pet: null,
    page: null,
    resultSearchPet: [],
    resultSearchNews: [],
    status: '',
    token: localStorage.getItem('token') || '',
    record: null,
    userLogin: localStorage.getItem('userLogin') || '',
    role: localStorage.getItem('role_name') || '',
    isLogin: localStorage.getItem('isLogin') || '',
    news: [],
    new: null,
    Category: null,
    recordNews: null,
    pageNews: null,
    notes: [],
    newsHome:[],
    productCate: [],
    products: [],
    themes: null,
    pet_home: null,
    rqPet: [],
    totalRqItem: null,
    newsCate: [],
    rqPet_stt1:[],
    rqStatePet: [],
    getAppointment: [],
    appointmentDetail: null,
    appointToday: null,
    rqPetStatus_Contact:[],
    products_Home: [],
    newsCategoryHome:[],
    checkNull: null,
    isLoading: 'endLoad',
    newsHomeByCate: [],
    employees: [],
    department: [],
    employeesId: null,
    rescues: [],
    employeesByDe:[],
    employeeRescue: null,
    petRescueOrder: [],
    petRescueId: null,
    RescueOrderId: null,
    detailRescue: [],
    fosterPet: [],
    petFoster: [],
    petFosterById: null,
    fosterBydId: null,
    detailFoster: [],
    employeeFoster: [],
    selectEmployeeFoster: null,
    petEntryType: [],
    petEntryStatus: [],
    petStatusEntry: [],
    petStatusType: [],
    employee_Rescue: [],
    employee_Foster: [],
    statistical: [],
    load: null,
    newHomeDetail: [],
}